// Auto-generated from comparisons.json — loaded via <script> tag for file:// compatibility
window.COMPARISONS_DATA = [
  {
    "id": "cmp-001-ball-curl",
    "date": "2026-02-10",
    "feature": "Ball Curl / Swerve Physics",
    "existsInFM2026": "yes",
    "existsInLegacy": "yes",
    "priority": "P2",
    "status": "open",
    "fm2026Details": "Magnus force model with perpendicular velocity vectors. Spin stored as ball.cvy (lateral) and ball.cvx (topspin). Curl force: spinFactor * (speed / 15.0) applied perpendicular to velocity direction. Topspin calculated from technique stat (>65). Spin dampens 95% per bounce (SPIN_DAMPING_GROUND=0.95). Constants: SPIN_FORCE_FACTOR=0.8, AIR_DRAG_COEFF=0.015.",
    "fm2026Files": ["ballEngine.js:469-480", "ballEngine.js:200-205", "physicsConstants.js:6-22"],
    "legacyDetails": "Polynomial equation-based curl. Curl stored as m_CurlVelocity (IntVector3). Formula: equation = 1 + (((v*v) * 0.5f) - (v * 1.5f)). Applied as: posx += (int)(equation * (pCVel.x * 0.003f)). Curl zeroed after bounce. Fixed curl divisor of 65. Constants: AIR_FRICTION=0.0002, curlamount=65.",
    "legacyFiles": ["Ball.cs:195-202", "Ball.cs:927-1026", "Ball.cs:282-287"],
    "gapAnalysis": "Different approaches: FM2026 uses physics-based Magnus force (simpler, more realistic), Legacy uses polynomial frame-dependent calculation (more complex, less physical). FM2026 adds topspin/backspin (Legacy has no vertical curl). FM2026 curl scales dynamically with ball speed; Legacy uses fixed divisor. FM2026 retains 95% spin per bounce; Legacy zeroes spin entirely on bounce.\n\nFM2026 is arguably MORE realistic here. Not a gap per se \u2014 different but valid approach.",
    "codeSuggestions": "No fix needed \u2014 FM2026's curl model is physically more accurate than Legacy's polynomial approach. However, if you want Legacy's more dramatic curl effect, you could increase SPIN_FORCE_FACTOR from 0.8 to 1.2 or add a polynomial curl component alongside the Magnus force."
  },
  {
    "id": "cmp-002-ball-collision",
    "date": "2026-02-10",
    "feature": "Ball Collision System (Post / Bar / Net)",
    "existsInFM2026": "yes",
    "existsInLegacy": "yes",
    "priority": "P2",
    "status": "open",
    "fm2026Details": "Post collision: 4 posts with FIFA geometry (52.5m, \u00b13.66m). Distance-based detection (BALL_RADIUS 0.11 + POST_RADIUS 0.06 = 0.17m). Vector reflection with restitution=0.6. Crossbar: 3 modes (under 50% bounce, over 70% bounce, face 40% reflection). Net: inside-goal zone detection with heavy damping (NET_DAMPING=12.0) and gravity assist. Emits BALL_COLLISION events.",
    "fm2026Files": ["ballEngine.js:549-572", "ballEngine.js:574-599", "ballEngine.js:601-612"],
    "legacyDetails": "Post collision: stamped debounce (200 frames). Angle-based deflection with deflectiondiff normalized to HALF_BALL_SIZE. X velocity reduced by factor z, Y/Z halved. Crossbar: height-based deflection, upper/lower bar calculations. Netting: back net 95% X cull, side net 75% Z cull, top net variants. Uses p=1-6 collision type identifiers.",
    "legacyFiles": ["Ball.cs:846-878", "Ball.cs:802-845", "Ball.cs:748-778"],
    "gapAnalysis": "FM2026 has modern physics-based collision (vector reflection, restitution coefficient). Legacy uses angle-based reduction with arbitrary multipliers. FM2026 adds explicit net damping zone (Legacy has separate net collision types). FM2026 uses continuous collision detection; Legacy uses stamped debounce.\n\nFM2026 is MORE COMPLETE here \u2014 it has post, crossbar, AND net detection. Legacy has more granular net collision types (back/side/top separately) but FM2026's approach is cleaner.",
    "codeSuggestions": "Consider adding separate net collision zones (back net vs side net vs top net) for more realistic ball behavior in the net, similar to Legacy's p=1,2,3,4 system. Currently FM2026 treats the entire goal zone with uniform damping."
  },
  {
    "id": "cmp-003-ball-trajectory",
    "date": "2026-02-10",
    "feature": "Ball Trajectory Prediction",
    "existsInFM2026": "partial",
    "existsInLegacy": "yes",
    "priority": "P0",
    "status": "open",
    "fm2026Details": "NO explicit trajectory prediction function. Uses frame-by-frame Euler integration only (ball.x += ball.vx * dt). Has intercept planning constants defined (INTERCEPT_LOOKAHEAD=2.0s, INTERCEPT_SAMPLE_DT=0.05s, INTERCEPT_MARGIN=0.3m) but no implementation found. AI cannot predict where the ball will land.",
    "fm2026Files": ["ballEngine.js:459-532", "physicsConstants.js:24-28"],
    "legacyDetails": "Explicit quadratic trajectory prediction. NewTimeBallWillBeClosest(): linear projection with 500-unit lookahead, dot-product based closest point calculation. NewTimeBallWillBeHeadable(): peak height calculation PHA=((vel.y/200f)+0.1f)*vel.y, with 10-element BallDropTable lookup. Time-to-ground: complex iterative calculation (max 2500 iterations) with flight percentage tracking.",
    "legacyFiles": ["Ball.cs:1483-1554", "Ball.cs:1557-1606", "Ball.cs:1332-1416"],
    "gapAnalysis": "CRITICAL GAP. FM2026 has no ball trajectory prediction at all \u2014 players cannot anticipate where the ball will land or be headable. Legacy has full predictive systems (closest point, headable height, time to ground). This affects:\n- Player positioning for headers\n- Interception timing\n- Goalkeeper positioning\n- Defensive clearance timing\n\nThe INTERCEPT constants are defined but unused \u2014 the implementation was never written.",
    "codeSuggestions": "// Add to ballEngine.js or new file ballPrediction.js\n\nfunction predictBallPosition(ball, futureTime) {\n  // Simple Euler forward simulation\n  let x = ball.x, y = ball.y, h = ball.height;\n  let vx = ball.vx, vy = ball.vy, vh = ball.vh;\n  const dt = 0.05; // 50ms steps\n  const steps = Math.ceil(futureTime / dt);\n  for (let i = 0; i < steps; i++) {\n    vx *= (1 - 0.015 * dt); // air drag\n    vy *= (1 - 0.015 * dt);\n    vh -= 9.81 * dt; // gravity\n    x += vx * dt;\n    y += vy * dt;\n    h += vh * dt;\n    if (h <= 0.11) { // ground bounce\n      vh = -vh * 0.65;\n      h = 0.11;\n      if (Math.abs(vh) < 0.5) vh = 0;\n    }\n  }\n  return { x, y, height: h, vx, vy, vh };\n}\n\nfunction timeToReachHeight(ball, targetHeight) {\n  // Binary search for when ball drops to targetHeight\n  let lo = 0, hi = 3.0; // max 3 seconds\n  for (let i = 0; i < 20; i++) {\n    const mid = (lo + hi) / 2;\n    const pred = predictBallPosition(ball, mid);\n    if (pred.height > targetHeight) lo = mid;\n    else hi = mid;\n  }\n  return (lo + hi) / 2;\n}\n\nfunction findInterceptPoint(ball, playerPos, playerSpeed) {\n  // Iterative: find time where player can reach ball position\n  for (let t = 0.1; t < 3.0; t += 0.05) {\n    const bp = predictBallPosition(ball, t);\n    const dist = Math.hypot(bp.x - playerPos.x, bp.y - playerPos.y);\n    if (dist <= playerSpeed * t + 0.3) return { time: t, pos: bp };\n  }\n  return null;\n}"
  },
  {
    "id": "cmp-004-ball-bounce",
    "date": "2026-02-10",
    "feature": "Ball Bounce Physics",
    "existsInFM2026": "yes",
    "existsInLegacy": "yes",
    "priority": "P2",
    "status": "open",
    "fm2026Details": "Bounce detection at height<=0.11m. Vertical restitution: 65% (BOUNCE_DAMPING=0.65). Curl-to-velocity transfer: 1.5x multiplier. Spin zeroed after bounce. Ground deceleration: 9.0 m/s\u00b2 (GROUND_DECEL). Stop threshold: |vh|<0.5 or planarSpeed<0.5 (ROLL_STOP_SPEED).",
    "fm2026Files": ["ballEngine.js:497-518", "physicsConstants.js:14-17"],
    "legacyDetails": "Vertical restitution: 50% (GROUND_BOUNCE=0.5). Horizontal friction: 20% (GROUND_BOUNCE_FRICTION=0.2). Curl-to-velocity transfer: 10x multiplier. Spin zeroed after bounce. Rolling friction: frame-dependent (GROUND_FRICTION=10 * frame * 0.5). Stop threshold: speed < GRAVITY/2.",
    "legacyFiles": ["Ball.cs:1029-1191", "Ball.cs:282-287"],
    "gapAnalysis": "Both have complete bounce physics with different parameters. FM2026 is MORE bouncy (65% vs 50% retention) but has less dramatic spin transfer (1.5x vs 10x). FM2026 uses constant deceleration (9 m/s\u00b2) which is more physically realistic than Legacy's frame-dependent friction.\n\nNo critical gap \u2014 different but both functional. FM2026 arguably more realistic.",
    "codeSuggestions": "Consider increasing curl-to-velocity transfer from 1.5x to something closer to 3-5x if balls feel too 'flat' after bouncing. The Legacy 10x is excessive but the current 1.5x may be too conservative for noticeable spin effects."
  },
  {
    "id": "cmp-005-movement-physics",
    "date": "2026-02-10",
    "feature": "Player Movement Physics",
    "existsInFM2026": "yes",
    "existsInLegacy": "yes",
    "priority": "P2",
    "status": "open",
    "fm2026Details": "Base speed: 3.2 m/s. Max speed formula: BASE_SPEED * (0.5 + (pace*0.7 + acceleration*0.3)/100). Sprint multiplier: 1.6x. Acceleration: 0.5 + accelSkill*4.0 m/s\u00b2. Deceleration: 2x acceleration. Urgency modifiers: critical 1.8x, high 1.3x. Dribbling speed: BASE_SPEED*0.85 + (pace*0.4+dribbling*0.4+control*0.2)/100*2.8. Collision avoidance: explicit distance-based repulsion. Separation forces: teammate 3.5m radius, opponent 1.0m. Anchor spring: 0.12 strength.",
    "fm2026Files": ["movementController.js:15-23", "movementController.js:61-99", "movementController.js:193-367"],
    "legacyDetails": "Abstract unit-based. Speed: (m_speed * Condition/100) * (Condition/100) \u2014 quadratic condition penalty. Acceleration: (m_acceleration * Condition)/100 \u2014 linear condition penalty. Min speed: 2 units/frame. Min acceleration: 10 units/frame. Movement via position-based pathfinding with target angles. Integer math (IntVector3). 145+ player states drive movement transitions.",
    "legacyFiles": ["Player.cs:917-932", "Player.cs:901-915", "PlayerAI.cs:1-150"],
    "gapAnalysis": "FM2026 has more sophisticated movement: explicit sprint, urgency scaling, collision avoidance, separation forces. Legacy has quadratic condition penalty (stat scaled twice by condition) which FM2026 lacks \u2014 FM2026 stamina only affects challenge probability, not movement speed directly.\n\nFM2026 MISSING: Legacy's quadratic condition-to-stat scaling (severely punishes low fitness). FM2026 has better: sprint system, urgency modifiers, collision avoidance fields.",
    "codeSuggestions": "Consider adding condition/fitness scaling to movement speed in FM2026:\n\n// In movementController.js, after maxSpeed calculation:\nconst fitnessRatio = player.stamina / player.staminaMax;\nconst fitnessPenalty = 0.7 + fitnessRatio * 0.3; // 70-100% speed based on stamina\nmaxSpeed *= fitnessPenalty;"
  },
  {
    "id": "cmp-006-pass-ai",
    "date": "2026-02-10",
    "feature": "Pass Decision AI / Scoring",
    "existsInFM2026": "yes",
    "existsInLegacy": "yes",
    "priority": "P1",
    "status": "open",
    "fm2026Details": "computePassIntent() with evaluatePass() scoring. Distance scoring: sweet spot 15-35m. Receiver pressure: 5m penalty radius. Strategic value: cutback detection (2.0x bonus), defender safety bias, progress bonus (1.3x for 5m+ gain). Blocking: 25\u00b0 safety cone with dynamic widening. Lead factor: 0.8 with time estimation (dist/15, clamped 3s). Vision cap: >25m AND vision<60 = 0.5x. Final score: 100 * distScore * pressureScore * tacticsScore.",
    "fm2026Files": ["aiPass.js:39-162", "aiPass.js:206-294", "aiPass.js:165-200"],
    "legacyDetails": "AIPassing() with FindOwnPassAngles(), OppositionPassAngleEffect(), ScorePassOptions(), BestPassOptions(). Lead factor: (55 + vision/2)/100 adjusted by dribbleEase. Distance scoring: discrete bands (5m, 20/30/40m). Angle scoring: perfect angle diff + facing angle + vision threshold. Safety angle: DRIBBLE_SAFETY_ANGLE*5 = 25\u00b0. Long ball bonus: progress toward goal + 100*ROTATION_SCALE. Vision check: myAngleDiff > (VisionStat + 90)\u00b0 = invalid.",
    "legacyFiles": ["PlayerAI.cs:75-111", "PlayerAI.cs:1670-1886", "PlayerAI.cs:1888-2051", "PlayerAI.cs:2054-2400"],
    "gapAnalysis": "Both have sophisticated pass scoring. FM2026 uses continuous normalized scoring (0-100); Legacy uses absolute scoring with discrete bands. FM2026 has explicit cutback detection; Legacy has better angle/facing integration.\n\nFM2026 MISSING:\n- Player pair chemistry bonuses (Legacy doesn't have this either, but FM2026 tracks playerFeeds without using them)\n- Repetition penalties (don't keep passing to same player)\n- Complex multi-angle vision checks\n- Weak foot integration into pass execution (FM2026 has this in ballActionController but unclear if pass AI considers it)\n\nFM2026 BETTER AT: cutback detection, continuous scoring, lead time estimation.",
    "codeSuggestions": "1. Use playerFeeds chemistry data in pass scoring:\n// In aiPass.js evaluatePass(), after tacticsScore:\nconst feedKey = `${passer.id}-${receiver.id}`;\nconst feeds = matchState.playerFeeds?.[feedKey] || 0;\nconst chemistryBonus = 1.0 + Math.min(feeds * 0.02, 0.15); // up to 15% bonus\nfinalScore *= chemistryBonus;\n\n2. Add repetition penalty:\nconst lastPassTarget = passer.lastPassTargetId;\nconst repetitionPenalty = (lastPassTarget === receiver.id) ? 0.7 : 1.0;\nfinalScore *= repetitionPenalty;"
  },
  {
    "id": "cmp-007-shot-ai",
    "date": "2026-02-10",
    "feature": "Shot Decision AI",
    "existsInFM2026": "yes",
    "existsInLegacy": "yes",
    "priority": "P2",
    "status": "open",
    "fm2026Details": "computeShotIntent() with computeShotScore(). Distance score: 1-(dist/(45+intel/100*5)). Angle score: 1-(dy/25). Pressure: per opponent within 4m, penalty 0.65+(intel/100)*0.15. Role bonus: strikers 1.08x within 25m. GK-aware aiming: calculates space left/right of keeper, shoots to larger gap. Accuracy: 5.5-18.5 base error, gaussian noise. Free kick: curl/dip from curve+technique stats. Penalties: 5 strategies (safe/power/precision/panenka/panic) based on confidence score.",
    "fm2026Files": ["aiShot.js:15-46", "aiShot.js:48-174", "aiShot.js:63-97", "aiShot.js:177-258"],
    "legacyDetails": "AIShooting() with maxDist calculation. Base: 18+(PowerStat/5). Modified by shooting flags (fromdistance +8, shootonsight +2, shootonclear -4). Opponent angle factor reduces threshold. Foot checking: weak foot penalty (200-WeakFootStat)/100. No explicit GK awareness. No free kick strategy. No penalty strategy. Uses FindShotTarget() for basic aiming.",
    "legacyFiles": ["PlayerAI.cs:629-878"],
    "gapAnalysis": "FM2026 is SIGNIFICANTLY MORE ADVANCED here:\n- GK-aware aiming (Legacy shoots at goal center)\n- Free kick curl/dip AI (Legacy has none)\n- Penalty 5-strategy system (Legacy has none)\n- Gaussian accuracy model (Legacy only has weak foot penalty)\n\nFM2026 MISSING: Weak foot penalty in shot scoring (handled separately in ballActionController).\n\nOverall FM2026 is SUPERIOR in shot AI.",
    "codeSuggestions": "No major fix needed. FM2026 shot AI is more advanced than Legacy. Minor enhancement: integrate weak foot awareness into shot DECISION (not just execution):\n\n// In aiShot.js computeShotScore(), add:\nconst isWeakSide = isOnWeakFootSide(player, goalPos);\nif (isWeakSide) distScore *= 0.85; // less likely to attempt weak-foot shot"
  },
  {
    "id": "cmp-008-dribble-ai",
    "date": "2026-02-10",
    "feature": "Dribbling AI",
    "existsInFM2026": "yes",
    "existsInLegacy": "yes",
    "priority": "P2",
    "status": "open",
    "fm2026Details": "computeDribbleIntent() with carry/gap/score calculations. Progress scoring (0.4-2.5x). Safety scoring (opponent proximity). Pressure: exponential retention (baseRetention^oppsNear). Solo run prevention: 40m limit. Boundary avoidance: 1.5m buffer with panic/caution penalties. Role bias: defenders 0.1x, attackers 2.0x. Game state: protecting lead 0.7x, chasing 1.2x. Heat map space integration. Gap exploitation: finds 4m+ gaps between defenders, knock-on if pace>75.",
    "fm2026Files": ["aiDribble.js:23-121", "aiDribble.js:124-155", "aiDribble.js:198-275", "aiDribble.js:278-288"],
    "legacyDetails": "FindDribbleDestination() + FindDribbleDirection() + FindDribbleSpeed(). GK targets goal directly. Wide men: directbias calculation with intelligence-based cut-inside decision. Ultimate destination logic: close to goal (<24m) or cutting = target goal. 360-degree gap scanning between defenders. Speed adjusted by opponent blocking. Keeper jink evasion. No explicit solo run prevention or boundary awareness.",
    "legacyFiles": ["PlayerAI.cs:1467-1579", "PlayerAI.cs:1581-1629", "PlayerAI.cs:882-950"],
    "gapAnalysis": "FM2026 is MORE COMPLETE:\n- Solo run prevention (Legacy lacks)\n- Boundary awareness (Legacy lacks)\n- Heat map space integration (Legacy lacks)\n- Explicit role/game-state biases (Legacy implicit)\n- Knock-on mechanic for fast players\n\nFM2026 MISSING:\n- 360-degree angle ordering (Legacy's gap scan is more thorough)\n- Intelligence-based cut-inside decision for wide players\n- Keeper jink evasion mechanic\n\nOverall FM2026 is SUPERIOR with better safety and tactical awareness.",
    "codeSuggestions": "Add intelligence-based cut-inside for wide players:\n// In aiDribble.js computeGapDribbleIntent():\nif (isWidePosition(player) && Math.abs(player.pos.y) > fieldWidth * 0.35) {\n  const cutChance = player.attributes.intelligence / 150;\n  if (rng.nextFloat() < cutChance) {\n    // Cut inside toward goal center\n    targetY = player.pos.y * 0.3; // Move toward center\n  }\n}"
  },
  {
    "id": "cmp-009-offball-movement",
    "date": "2026-02-10",
    "feature": "Off-Ball Movement / Player Runs",
    "existsInFM2026": "yes",
    "existsInLegacy": "yes",
    "priority": "P1",
    "status": "open",
    "fm2026Details": "computeOffBallIntent() with attacking runs (5 types: straight burst, half-space 'Henry' run, diagonal cuts, far post, target box), support runs (limited to closest 1 player, 6-32m from ball), marking (role-based priority: CBs mark STs priority 30, etc.), communication (askingForBall flag), offside correction. Marking has zonal responsibility, occupancy penalty (-1000 if closer teammate), tight marking within 8m. Man-to-man flag reduces lane discipline.",
    "fm2026Files": ["aiOffBall.js:42-184", "aiOffBall.js:188-298", "aiOffBall.js:301-375", "aiOffBall.js:436-618"],
    "legacyDetails": "PlayerInMotion() with AnyForwardRun(), AnyBackwardRun(), FindSpace(), AnyMarking(), GetTacticTarget(). Heat map for space finding. Offside check with agility factor. Sprint decision: ShallWeSprint() based on last defender position. Position fade for smooth transitions. FreeRoleFlag enables space-finding mode.",
    "legacyFiles": ["PlayerActions.cs:317-551"],
    "gapAnalysis": "FM2026 ADVANTAGES:\n- 5 explicit attacking run types (Legacy has generic forward/backward)\n- Player communication (askingForBall)\n- Sophisticated marking with role priority and occupancy prevention\n- Support run limiting (prevents mob behavior)\n\nFM2026 MISSING:\n- Detailed AnyForwardRun/AnyBackwardRun specifics (Legacy implementation hidden)\n- Position fade for smooth transitions\n- Sprint-based-on-offside-line logic\n\nBoth engines use heat maps for space finding. FM2026 is more explicit and tactical.",
    "codeSuggestions": "Consider adding position smoothing/fade to prevent abrupt position changes:\n// In movementController.js:\nconst FADE_FACTOR = 0.85;\nplayer.targetPos.x = player.pos.x * (1 - FADE_FACTOR) + targetX * FADE_FACTOR;\nplayer.targetPos.y = player.pos.y * (1 - FADE_FACTOR) + targetY * FADE_FACTOR;"
  },
  {
    "id": "cmp-010-space-finding",
    "date": "2026-02-10",
    "feature": "Space Finding AI",
    "existsInFM2026": "yes",
    "existsInLegacy": "yes",
    "priority": "P2",
    "status": "open",
    "fm2026Details": "buildHeatMap(): 18x15 grid (5.83m x 4.53m cells). Heat generation: +1.0 at player pos, +0.5 adjacent (diffusion). findOpenPocket(): role-specific search radius (FW=1, MID=3 cells), move if bestScore>2.0. calculateSpaceScore(): horizontal+vertical scan for empty cells. calculateGapRun(): finds gaps >8m between defenders, positions on shoulder of last defender. Offside-aware.",
    "fm2026Files": ["aiSpace.js:44-69", "aiSpace.js:81-117", "aiSpace.js:119-149", "aiSpace.js:155-247"],
    "legacyDetails": "CreateHeatMap() + FindSpace() referenced in PlayerActions.cs. 15x18 grid (same coverage as FM2026 but inverted labels). Implementation details hidden but used for open pocket finding near tactical target. Both engines use 8m gap threshold.",
    "legacyFiles": ["PlayerActions.cs:342-354", "Team.cs:870-877"],
    "gapAnalysis": "FM2026 is more transparent and explicit. Adds: heat diffusion, role-specific search radius, gap running with offside awareness. Legacy is opaque \u2014 implementation hidden. Both use identical grid coverage.\n\nNo significant gaps \u2014 FM2026 is more sophisticated here.",
    "codeSuggestions": "No fix needed. FM2026 space finding is well-implemented."
  },
  {
    "id": "cmp-011-tackling",
    "date": "2026-02-10",
    "feature": "Tackling Variants",
    "existsInFM2026": "partial",
    "existsInLegacy": "yes",
    "priority": "P0",
    "status": "open",
    "fm2026Details": "Single unified challenge system. No distinct tackle types. Success probability: 0.55 + skillDiff/120 + spacingBonus + fatiguePenalty*0.08 + frontBonus. Tackles from behind: 2.5x foul multiplier. Defender box fortress: +0.20 in own box. GK bonus: +0.25 in penalty area. Cooldowns: win 1.2s, fail 1.8s. Constants: PICKUP_RADIUS=1.2m, OWNER_STUMBLE_S=0.4s.",
    "fm2026Files": ["challengeController.js:32-225", "challengeController.js:358-424"],
    "legacyDetails": "4 distinct tackle variants based on angle difference:\n1. Block Tackle (angle>100\u00b0): standing block, 250ms duration\n2. Swivel Tackle (angle 75-100\u00b0): spinning defensive move, 840ms\n3. Slide Tackle (angle<75\u00b0): committed full-length, 1100ms safe / 900ms wild\nEach has normal+hard variant (aggression roll: random(0,350) < agg). Predicted ball position accounts for opponent speed vector. Animation-driven timing.",
    "legacyFiles": ["PlayerActions.cs:1105-1245", "PlayerState.cs:blocktackle/slidetackle states"],
    "gapAnalysis": "CRITICAL GAP. FM2026 has ONE tackle type; Legacy has FOUR with angle-based selection plus hard/normal variants (8 total combinations). FM2026 lacks:\n- Block tackle vs slide tackle distinction\n- Angle-based tackle selection\n- Hard/normal variant based on aggression\n- Duration-based risk (slide tackle = longer recovery = riskier)\n- Animation-tied timing",
    "codeSuggestions": "// Add to challengeController.js, in the challenge resolution:\n\nfunction selectTackleType(tackler, owner, angleDiff) {\n  const agg = tackler.attributes?.aggression ?? 50;\n  const isHard = Math.random() * 350 < agg;\n  \n  let type, duration, foulRisk;\n  if (angleDiff > 100) {\n    type = isHard ? 'BLOCK_HARD' : 'BLOCK';\n    duration = 0.25; // 250ms\n    foulRisk = isHard ? 0.15 : 0.05;\n  } else if (angleDiff > 75) {\n    type = isHard ? 'SWIVEL_HARD' : 'SWIVEL';\n    duration = 0.84; // 840ms\n    foulRisk = isHard ? 0.25 : 0.10;\n  } else {\n    type = isHard ? 'SLIDE_WILD' : 'SLIDE_SAFE';\n    duration = isHard ? 0.9 : 1.1;\n    foulRisk = isHard ? 0.35 : 0.15;\n  }\n  \n  return { type, duration, foulRisk, isHard };\n}\n\n// Integrate into resolveChallenge():\nconst angleDiff = calculateAngleDiff(tackler, owner);\nconst tackle = selectTackleType(tackler, owner, angleDiff);\n// Apply duration as cooldown, foulRisk as additional foul probability"
  },
  {
    "id": "cmp-012-fouls",
    "date": "2026-02-10",
    "feature": "Foul Types and Referee Decisions",
    "existsInFM2026": "partial",
    "existsInLegacy": "yes",
    "priority": "P0",
    "status": "open",
    "fm2026Details": "Single CHALLENGE_FOUL event with random severity. Foul chance: 0.05 + (aggression/400) - (tackling/300). Modifiers: stayonfeet -60%, noprisoners +220%, from-behind 2.5x. Card: severity roll 0-0.70 none, 0.70-0.96 yellow, 0.96-1.00 red. Threshold adjusted by aggression. No foul type distinction. All fouls detected (no 'seeing' mechanic).",
    "fm2026Files": ["challengeController.js:227-295"],
    "legacyDetails": "7 distinct foul types: standardFoul, violentConduct (red), professionalFoul (red), handBall (red), verbalFoul (yellow), offside, simulation/diving (yellow). Card logic: standard/verbal/simulation \u2192 yellow, second yellow \u2192 red. Violent/handball/professional \u2192 direct red. Referee 'sees' incident randomly (m_sight=100). Queue-based processing with busy check.",
    "legacyFiles": ["Officials.cs:13-23", "Officials.cs:112-132", "OfficialLogic.cs"],
    "gapAnalysis": "CRITICAL GAP. FM2026 has ONE generic foul type with random card severity. Legacy has 7 specific types with type-determined cards. FM2026 lacks:\n- Violent conduct (always red)\n- Professional foul detection (tactical foul \u2192 red)\n- Handball detection\n- Simulation/diving detection\n- Verbal abuse\n- Referee visibility mechanic\n- Type-based card logic (fouls ALWAYS mean yellow/red based on type, not random roll)",
    "codeSuggestions": "// Replace random severity with type-based system in challengeController.js:\n\nconst FOUL_TYPES = {\n  STANDARD: { card: 'YELLOW', chance: 0.60 },\n  VIOLENT: { card: 'RED', chance: 0.08 },\n  PROFESSIONAL: { card: 'RED', chance: 0.05 },\n  HANDBALL: { card: 'RED', chance: 0.02 },\n  SIMULATION: { card: 'YELLOW', chance: 0.03 },\n  VERBAL: { card: 'YELLOW', chance: 0.02 },\n};\n\nfunction determineFoulType(tackler, victim, context) {\n  if (context.fromBehind && context.lastManBack) return 'PROFESSIONAL';\n  if (context.relativeSpeed > 8 && tackler.attributes.aggression > 80) return 'VIOLENT';\n  if (context.ballHandled) return 'HANDBALL';\n  return 'STANDARD';\n}\n\nfunction determineCard(foulType) {\n  const info = FOUL_TYPES[foulType];\n  if (info.card === 'RED') return 'RED';\n  return 'YELLOW'; // All non-red fouls are yellow\n}"
  },
  {
    "id": "cmp-013-cards",
    "date": "2026-02-10",
    "feature": "Card System (Yellow / Red)",
    "existsInFM2026": "partial",
    "existsInLegacy": "yes",
    "priority": "P0",
    "status": "open",
    "fm2026Details": "Cards tracked via eventController.js (stats.yellowCards++, stats.redCards++, pStats.yellow_cards++, pStats.red_cards++). Card type determined during tackle in checkForceFoul(). NO second yellow \u2192 red card logic found. No accumulation tracking on player object.",
    "fm2026Files": ["eventController.js:138-146", "challengeController.js:93-123"],
    "legacyDetails": "Explicit second yellow \u2192 red card logic. Yellow triggers: standardFoul, verbalFoul, simulation. If yellowCards>1 \u2192 GiveRedCard() + SecondYellow animation. Red triggers: violentConduct, professionalFoul, handBall. Adds 6 seconds injury time per card. Official animation states (showyellow, showred).",
    "legacyFiles": ["Officials.cs:112-132", "OfficialLogic.cs:167-202"],
    "gapAnalysis": "CRITICAL GAP. FM2026 has NO second yellow = red card logic. Cards are counted in stats but never checked against each other. A player could receive 5 yellow cards without being sent off.\n\nAlso missing: injury time added per card, card accumulation check, official animations.",
    "codeSuggestions": "// Add to eventController.js in the CARD case:\ncase 'CARD':\n  if (payload.cardType === 'YELLOW') {\n    stats.yellowCards++;\n    pStats.yellow_cards++;\n    // CHECK FOR SECOND YELLOW\n    if (pStats.yellow_cards >= 2) {\n      payload.cardType = 'RED'; // Upgrade to red\n      stats.redCards++;\n      pStats.red_cards++;\n      player.onPitch = false; // Send off\n      player.role = 'SENT_OFF';\n      this.emit('SEND_OFF', teamIdx, playerId);\n    }\n  } else if (payload.cardType === 'RED') {\n    stats.redCards++;\n    pStats.red_cards++;\n    player.onPitch = false;\n    player.role = 'SENT_OFF';\n    this.emit('SEND_OFF', teamIdx, playerId);\n  }\n  // Add injury time\n  this.match.injuryTime = (this.match.injuryTime || 0) + 6;\n  break;"
  },
  {
    "id": "cmp-014-offside",
    "date": "2026-02-10",
    "feature": "Offside Detection",
    "existsInFM2026": "yes",
    "existsInLegacy": "yes",
    "priority": "P1",
    "status": "open",
    "fm2026Details": "Timing-based at pass launch. Sorts opponents by distance to goal line, gets second-last (index 1). Marks teammates in opponent half + ahead of ball + ahead of second-last. Enforcement: 5-second window from pass. If receiver is in offsideIds and same team as passer \u2192 OFFSIDE event + restart.",
    "fm2026Files": ["ballEngine.js:219-265", "gameEngine.js:182-213"],
    "legacyDetails": "AreTheyOffside() used during pass evaluation. Offside flag on player data (m_offside). Linesman raises flag (TriggerOffsideFlagEast/West). Game stops for free kick. Offside trap possible via marking system. Immediate enforcement.",
    "legacyFiles": ["PlayerAI.cs:1631-1698", "Officials.cs:71-78", "GameState.cs"],
    "gapAnalysis": "Both engines detect offside correctly. Key differences:\n- FM2026: frozen at pass moment (static), 5-second enforcement window\n- Legacy: checked during pass evaluation (proactive), immediate enforcement\n- FM2026 MISSING: dynamic offside trap, linesman animation\n- FM2026 ISSUE: 5-second window may allow late false flags or missed calls on rebounds\n- FM2026 MISSING: offside only on passes, not on free-kick reception or rebounds",
    "codeSuggestions": "1. Reduce 5-second window to 2 seconds:\n// gameEngine.js line 188:\nif ((matchState.timeSeconds - passOffsideState.timestamp) < 2.0) { // was 5.0\n\n2. Clear offside state on any ball contact by non-offside player:\n// After ball ownership change, if new owner is NOT in offsideIds, clear state\nif (newOwner && !ball.passOffsideState?.offsideIds?.includes(newOwner.id)) {\n  ball.passOffsideState = null;\n}"
  },
  {
    "id": "cmp-015-aerial-heading",
    "date": "2026-02-10",
    "feature": "Aerial Challenges / Heading",
    "existsInFM2026": "yes",
    "existsInLegacy": "yes",
    "priority": "P1",
    "status": "open",
    "fm2026Details": "Aerial contender detection: AERIAL_MIN_HEIGHT=0.8m, AERIAL_MAX_HEIGHT=2.8m, BASE_REACH_RADIUS=1.8m (+ jumping/200 bonus). Duel win score: (jumping*0.4 + strength*0.4) * (0.8 + stamina/100*0.2) * distance factor * random variance (0.8-1.2). Header direction: shoot if <20m from goal, clearance if defending <15m, else pass to teammate 5-25m. Accuracy: noise = (100-headingAttr)/5 degrees.",
    "fm2026Files": ["aerialChallengeController.js:29-31", "aerialChallengeController.js:41-73", "aerialChallengeController.js:78-100", "aerialChallengeController.js:105-159"],
    "legacyDetails": "Three heading height zones (High >1m, Mid 0.6-1m, Low <0.6m) with different animations each. Distance detection: <=1.25m. Power: 13000 + 130*HeadingStat. Direction: shoot if <18 ROTATION_SCALE, else pass. Accuracy: GetRandom(0,130) < HeadingStat for success. GK handling: catch vs parry based on ball speed (skill = (400+HandlingStat*6)*ROTATION_SCALE/120).",
    "legacyFiles": ["PlayerActions.cs:1668-1920", "PlayerActions.cs:4324-4403", "KeeperActions.cs:820-856"],
    "gapAnalysis": "FM2026 MISSING:\n- Height-zone differentiation (Legacy has High/Mid/Low with different animations and difficulty)\n- Fixed height band (0.8-2.8m) vs dynamic player reach\n- No 'receiving header' pre-animation state\n- GK aerial handling not explicit in aerialChallengeController\n\nFM2026 BETTER AT:\n- Explicit duel win-score calculation (Legacy is timing-based)\n- Noise-based accuracy model\n- Stamina integration in aerial duels",
    "codeSuggestions": "Add height-zone differentiation:\n// In aerialChallengeController.js, after win score calculation:\nlet heightZone, difficultyMod;\nif (ball.height > 2.0) { heightZone = 'HIGH'; difficultyMod = 1.0; }\nelse if (ball.height > 1.2) { heightZone = 'MID'; difficultyMod = 0.9; }\nelse { heightZone = 'LOW'; difficultyMod = 0.75; } // harder to head low balls\n\n// Apply to accuracy noise:\nnoise = ((100 - headingAttr) / 5) / difficultyMod;"
  },
  {
    "id": "cmp-016-goalkeeper",
    "date": "2026-02-10",
    "feature": "Goalkeeper Dive System",
    "existsInFM2026": "yes",
    "existsInLegacy": "yes",
    "priority": "P1",
    "status": "open",
    "fm2026Details": "Implicit continuous system. attemptGoalkeeperSave(): reach-based, catch vs parry vs punch decision. Reaction delay: 0.15-0.4s (agility/intel/confidence). Visibility delay: +50ms per blocker. Save score: (shotStopping/100)*psychMod - (difficulty*0.4). Catch if speed<26.5, height<2.6, within GK_CATCH_RADIUS. Punch if height>1.8 or speed>22. Parry otherwise. Recovery: 1.8-(agility/100)*0.8s. 1v1 charging: 10-25m range based on braveness. Sweep: 12+(agility/100)*6m radius.",
    "fm2026Files": ["aiKeeper.js:129-251", "aiKeeper.js:373-428", "aiKeeper.js:55-120", "aiKeeper.js:256-292", "aiKeeper.js:286-368", "aiKeeper.js:297-323"],
    "legacyDetails": "12 explicit dive types: 3 heights (Low/Mid/High) x 2 directions (Left/Right) x 2 distances (Close/Far). Direction: angle to ball vs GK facing. Distance threshold: ROTATION_SCALE*2 + (ShotStoppingStat/120). Height thresholds: 0.75, 1.5, 2.1 ROTATION_SCALE. Reaction: animation-based 150-578ms. Catch vs parry: StrikeStamp < GameTime = must parry. Distribution after save.",
    "legacyFiles": ["KeeperActions.cs:1985-2207", "KeeperActions.cs:1870-1880", "KeeperActions.cs:1919-1923"],
    "gapAnalysis": "Different approaches:\n- Legacy: 12 discrete dive states with animation-driven timing (more visual)\n- FM2026: continuous reach-based system (more physics-based)\n\nFM2026 BETTER AT: punch mechanic, 1v1 charging logic, sweep logic, blocker visibility delay\nFM2026 MISSING: 12-type granularity (for animation mapping), explicit catch timing (StrikeStamp), distribution after save\n\nFor a headless server simulation, FM2026's approach is arguably better. The 12-type system is mainly needed for animation rendering.",
    "codeSuggestions": "If you need to map saves to animation types for replay rendering, add:\n// After save decision in aiKeeper.js:\nfunction classifyDive(ball, gk) {\n  const height = ball.height > 2.0 ? 'HIGH' : ball.height > 1.0 ? 'MID' : 'LOW';\n  const direction = ball.y > gk.pos.y ? 'RIGHT' : 'LEFT';\n  const dist = Math.hypot(ball.x - gk.pos.x, ball.y - gk.pos.y);\n  const distance = dist > 3.0 ? 'FAR' : 'CLOSE';\n  return `${height}_${direction}_${distance}`; // e.g. 'MID_LEFT_FAR'\n}"
  },
  {
    "id": "cmp-017-corners",
    "date": "2026-02-10",
    "feature": "Set Pieces \u2014 Corner Kicks",
    "existsInFM2026": "partial",
    "existsInLegacy": "yes",
    "priority": "P0",
    "status": "open",
    "fm2026Details": "Corner awarded when ball out on goal line + last touch by attacker. Spot at corner flag (\u00b152.5, \u00b134). Taker: closest non-GK. NO defensive positioning. NO attacking corner routines. NO short corner option. Players stay in-play positions. Corner instruction exists as numeric value but implementation unclear.",
    "fm2026Files": ["matchFlowController.js:450-469", "matchFlowController.js:792-799"],
    "legacyDetails": "Defensive corner roles: nearpost (1 CB), farpost (1 CB), zonal (4-5 players), covershort (1 winger), marker (optional). Short corner option via cornerFlag==3 with secondary helper. Taker selected via SetCornerTaker(). Uses BallGrid tactic system for positioning. Attacking corners had code but commented out.",
    "legacyFiles": ["GameState.cs:847", "Team.cs:946-1592", "GameState.cs:1734-1760"],
    "gapAnalysis": "CRITICAL GAP. FM2026 has NO defensive corner positioning \u2014 all players stay in open-play positions during corners. This means:\n- No near post marker\n- No far post marker\n- No zonal defensive line\n- No short corner cover\n- Corners are essentially free headers for the attacking team\n\nThis is one of the most impactful missing features for match realism.",
    "codeSuggestions": "// Add corner positioning to matchFlowController.js:\n\nfunction setupCornerDefense(team, cornerSide) {\n  const goalX = team.attackingGoalX === 52.5 ? -52.5 : 52.5;\n  const roles = [\n    { role: 'nearpost', pos: { x: goalX, y: cornerSide * 2.5 } },\n    { role: 'farpost', pos: { x: goalX, y: cornerSide * -5.0 } },\n    { role: 'zonal1', pos: { x: goalX + 4, y: -2 } },\n    { role: 'zonal2', pos: { x: goalX + 4, y: 2 } },\n    { role: 'zonal3', pos: { x: goalX + 6, y: 0 } },\n    { role: 'edge', pos: { x: goalX + 12, y: cornerSide * 8 } },\n  ];\n  // Assign defenders to roles by priority (CBs first)\n  const defenders = team.players.filter(p => p.onPitch && p.role !== 'GK')\n    .sort((a, b) => defPriority(a.role) - defPriority(b.role));\n  roles.forEach((r, i) => {\n    if (defenders[i]) {\n      defenders[i].cornerTarget = r.pos;\n      defenders[i].cornerRole = r.role;\n    }\n  });\n}"
  },
  {
    "id": "cmp-018-free-kicks",
    "date": "2026-02-10",
    "feature": "Set Pieces \u2014 Free Kicks",
    "existsInFM2026": "yes",
    "existsInLegacy": "yes",
    "priority": "P1",
    "status": "open",
    "fm2026Details": "Direct/indirect based on distance (DIRECT_KICK_RANGE=28m). Wall: 9.15m distance, 2-5 players by distance (5 if <20m, 4 if <25m, 3 if <30m, reduced by 2 if wide). Perpendicular spacing 0.6m. Direct FK shot: curl from curve stat (>60), dip from technique (>60), aims opposite corner. Taker: nearest non-GK (no override). No short FK option.",
    "fm2026Files": ["matchFlowController.js:578-589", "matchFlowController.js:809-875", "matchFlowController.js:771-779", "aiShot.js:63-97"],
    "legacyDetails": "Direct vs indirect based on offense type. Wall: 9.15m, angle-based rotation with perpendicular spread. Taker: closest free player OR FreeKickTaker override. Short FK option via cornerFlag==3 with helper. Training attribute (m_training_freekicks) affects quality. Prone check prevents injured taker.",
    "legacyFiles": ["GameState.cs:1196-1260", "GameState.cs:1797-1818", "GameState.cs:1763-1795"],
    "gapAnalysis": "FM2026 MISSING:\n- Designated free kick taker override (always nearest player)\n- Short free kick option\n- Training attribute impact\n- Injured player check for taker\n\nFM2026 BETTER AT:\n- Wall size algorithm (distance-based, granular)\n- Direct FK curl/dip physics (Legacy has no specific FK shot logic)\n- Wall perpendicular spacing calculations",
    "codeSuggestions": "// Add FK taker override to matchFlowController.js:\nfunction selectFreeKickTaker(team, fkSpot) {\n  // Check for designated FK taker first\n  const designated = team.players.find(p => \n    p.onPitch && p.role !== 'GK' && \n    (p.attributes?.freeKickTaker || p.attributes?.curve > 75)\n  );\n  if (designated) return designated;\n  // Fallback to nearest\n  return findNearestNonGK(team, fkSpot);\n}"
  },
  {
    "id": "cmp-019-penalties",
    "date": "2026-02-10",
    "feature": "Set Pieces \u2014 Penalties",
    "existsInFM2026": "yes",
    "existsInLegacy": "yes",
    "priority": "P1",
    "status": "open",
    "fm2026Details": "Taker: sorted by penalties attribute. Shooter: 5 strategies (safe \u00b11m, power \u00b12.5m, precision \u00b12.8-3.4m, panenka center, panic) based on confidence score (penalties*0.5 + composure*0.3 + confidence*0.2). Accuracy modifier from finishing stat. GK: random L/C/R guess, no anticipation (1% cheat if anticipation>90). GK uses standard save logic after dive.",
    "fm2026Files": ["aiShot.js:177-258", "aiKeeper.js:373-428", "matchFlowController.js:292-340"],
    "legacyDetails": "Taker: closest free player with ball control. GK: uses same 12-type dive system. Training attribute (m_training_penalties) affects GK prediction accuracy. If training < threshold, ball position randomized for GK. Penalty shootout support with separate states.",
    "legacyFiles": ["KeeperActions.cs:1870-2207", "GameState.cs:1197-1210"],
    "gapAnalysis": "FM2026 BETTER AT: shooter strategies (5 types), confidence-based selection, taker sorted by penalty attribute\nFM2026 MISSING:\n- GK penalty save intelligence (just random L/C/R guess)\n- No GK reaction time model for penalties\n- No anticipation based on taker tendency\n- No training attribute for GK prediction\n\nThe GK penalty logic is the weakest part \u2014 penalty shootouts are essentially random for the keeper.",
    "codeSuggestions": "// Improve GK penalty logic in aiKeeper.js:\nfunction computePenaltySaveIntent(gk, ball, rng) {\n  const anticipation = gk.attributes?.anticipation ?? 50;\n  const reflex = gk.attributes?.reflexes ?? 50;\n  \n  // Skill-based prediction (not just random)\n  let guessWeights = [0.33, 0.34, 0.33]; // L, C, R base\n  if (anticipation > 70) {\n    // Better keepers bias toward corners\n    guessWeights = [0.40, 0.20, 0.40];\n  }\n  \n  // Reaction delay based on reflexes\n  const reactionDelay = 0.3 - (reflex / 100) * 0.15; // 0.15-0.30s\n  \n  // Choose direction based on weighted random\n  const roll = rng.nextFloat();\n  let dir = roll < guessWeights[0] ? -1 : roll < guessWeights[0] + guessWeights[1] ? 0 : 1;\n  \n  return { dir, reactionDelay };\n}"
  },
  {
    "id": "cmp-020-throwin-goalkick",
    "date": "2026-02-10",
    "feature": "Set Pieces \u2014 Throw-ins & Goal Kicks",
    "existsInFM2026": "partial",
    "existsInLegacy": "partial",
    "priority": "P2",
    "status": "open",
    "fm2026Details": "Throw-in: taker is closest non-GK, non-ST. Treated as standard pass. No special throw mechanics or formation. Goal kick: GK selected, treated as standard restart. No explicit kick power/distance model. No special positioning or target selection.",
    "fm2026Files": ["matchFlowController.js:441-443", "matchFlowController.js:762-770", "matchFlowController.js:450-459"],
    "legacyDetails": "Throw-in: closest free player. Standard throw mechanics. No special formation. Goal kick: GK with run-up animation (6.25m offset), 3 states (positioning/prep/approach). Explicit kick power (21000 units) and height (15000 units). Target selection via FindGoalKickTarget(). Inaccuracy effect applied. Receiving header state assigned proactively.",
    "legacyFiles": ["GameState.cs:988-998", "KeeperActions.cs:191-320"],
    "gapAnalysis": "Both engines are minimal on throw-ins. For goal kicks, FM2026 MISSING:\n- GK run-up animation states\n- Specialized kick power/distance model\n- Target selection function\n- Inaccuracy model\n- Proactive heading assignment for receiver",
    "codeSuggestions": "// Add goal kick specialization to matchFlowController.js or aiKeeper.js:\nfunction computeGoalKickIntent(gk, teammates) {\n  const power = 20 + (gk.attributes?.kicking ?? 50) / 5; // 20-30 m/s\n  const loft = 4.0; // high ball\n  // Find best target: prefer defenders/midfielders 25-40m away\n  const targets = teammates.filter(t => t.role !== 'GK' && t.onPitch)\n    .map(t => ({ player: t, dist: distance(gk.pos, t.pos) }))\n    .filter(t => t.dist > 20 && t.dist < 45)\n    .sort((a, b) => a.dist - b.dist);\n  const target = targets[0]?.player || teammates[1]; // fallback\n  return { target, power, loft };\n}"
  },
  {
    "id": "cmp-021-formations-tactics",
    "date": "2026-02-10",
    "feature": "Formation / Tactical Instructions",
    "existsInFM2026": "yes",
    "existsInLegacy": "yes",
    "priority": "P1",
    "status": "open",
    "fm2026Details": "18x15 grid (much finer than Legacy). 3 position variants per formation: main, run, pass. Team instructions: passingStyle (simple/forward/longball/quick), pressing (none/deep/high), tempo, possession, corner, squeeze. Player flags: MarkingFlag (mantoman/zonal), ShootingFlag (4 opts), TacklingFlag (3 opts), MovementFlag (4 opts), PassingFlag (5 opts), CrossingFlag (3 opts). Conditional instructions: time-based + score-based triggers for formation/sub/tactic changes.",
    "fm2026Files": ["tacticsController.js:88-107", "tacticsController.js:109-117", "tacticsController.js:124-175"],
    "legacyDetails": "6x5 grid (30 positions). BallGrid[6x5] system: 30 tactic blocks with player positions per ball zone. Out-of-possession compression: 3 levels (deep 70%/60%, mid 85%/75%, high 100%/90%). Corner roles: nearpost, farpost, zonal, covershort, marker. Dribble bias indexed by role. Formation scaling for kickoff/goal-kick specific positioning.",
    "legacyFiles": ["Tactics.cs:10-12", "Tactics.cs:102-215", "Tactics.cs:325-373"],
    "gapAnalysis": "FM2026 BETTER AT: finer grid (270 vs 30 cells), conditional instructions, per-player tactical flags, multiple formation variants\nFM2026 MISSING:\n- BallGrid system (positions that change based on WHERE the ball is \u2014 very sophisticated)\n- Out-of-possession compression (3 defensive levels)\n- Dribble bias per role\n- Corner-specific roles in formation\n- Kickoff/goal-kick specific positioning\n\nThe BallGrid is the biggest gap \u2014 it means Legacy formations are dynamic (change with ball position) while FM2026 formations are static.",
    "codeSuggestions": "// Add ball-zone-based positioning to tacticsController.js:\nfunction getPositionForBallZone(player, ballPos, formation) {\n  // Divide pitch into 6 zones along X axis\n  const zoneX = Math.floor((ballPos.x + 52.5) / 17.5); // 0-5\n  const zoneKey = Math.min(5, Math.max(0, zoneX));\n  \n  // Each formation should have 6 position variants\n  const positions = formation.ballZonePositions?.[zoneKey];\n  if (positions && positions[player.formationIdx]) {\n    return positions[player.formationIdx];\n  }\n  return formation.positions[player.formationIdx]; // fallback\n}"
  },
  {
    "id": "cmp-022-player-states",
    "date": "2026-02-10",
    "feature": "Player States / State Machine",
    "existsInFM2026": "partial",
    "existsInLegacy": "yes",
    "priority": "P1",
    "status": "open",
    "fm2026Details": "10 core states: HOLD_SHAPE, PRESS, COVER, MARK, SUPPORT, DRIBBLE, PASS, SHOOT, RECEIVE, IDLE, MOVE, CONTROL. State locking prevents rapid switching (PRESS 600ms, COVER 500ms, MARK 700ms, etc.). Hysteresis check prevents PRESS\u2194COVER within 600ms. Decision interval: 0.15-0.4s based on vision/composure.",
    "fm2026Files": ["playerStateController.js:137-150", "playerStateController.js:43-84", "playerStateController.js:115-124"],
    "legacyDetails": "145 explicit states covering: standing (2), movement (5), ball interaction (16), tackling (4), injury/stumbling (14), celebrations (4), set pieces (16), goalkeeper (22+), substitution (4), ejection/shootout (3), plus many more. Pending state queue for handling state changes while busy. State lifecycle: SetState(state, busy, forced).",
    "legacyFiles": ["PlayerState.cs:13-145"],
    "gapAnalysis": "FM2026 has 10 states vs Legacy's 145. However, FM2026 is a headless server simulation \u2014 it doesn't need animation states. The states map to AI decisions, not visual states.\n\nStill MISSING and RELEVANT for headless sim:\n- Goalkeeper-specific states (no dive variants, positioning modes)\n- Set piece states (no FK/corner/penalty taker states)\n- Injury recovery states\n- Celebration states (for replay timing)\n- Tackle type states\n\nThe 10-state system is adequate for AI decision-making but insufficient for replay rendering variety.",
    "codeSuggestions": "For replay rendering, add a secondary 'action' state that maps to animation:\n\n// Add to playerStateController.js:\nconst ACTION_STATES = {\n  IDLE: 'idle', RUNNING: 'running', SPRINTING: 'sprinting',\n  PASSING: 'passing', SHOOTING: 'shooting', HEADING: 'heading',\n  BLOCK_TACKLE: 'blocktackle', SLIDE_TACKLE: 'slidetackle',\n  DIVING_LOW: 'diving_low', DIVING_MID: 'diving_mid', DIVING_HIGH: 'diving_high',\n  CELEBRATING: 'celebrating', INJURED: 'injured', RECEIVING: 'receiving'\n};\nfunction setActionState(player, action, duration) {\n  player.actionState = action;\n  player.actionUntil = Date.now() + duration;\n}"
  },
  {
    "id": "cmp-023-stamina",
    "date": "2026-02-10",
    "feature": "Stamina / Fatigue System",
    "existsInFM2026": "yes",
    "existsInLegacy": "partial",
    "priority": "P2",
    "status": "open",
    "fm2026Details": "Active drain model. Permanent decay: 0.005/sec (loses ~27 stamina over 90min). Recovery at speed<1.0 m/s: +2.5/sec. Drain at speed>=1.0 m/s: 0.05 + (effort\u00b2)*4.0 per sec (jog 3m/s = 0.48/sec, sprint 8m/s = 3.22/sec). Stamina affects challenge win chance (+8% per 100% fatigue). StaminaMax decays permanently.",
    "fm2026Files": ["playerStateController.js:166-209", "playerStateController.js:9-13", "challengeController.js:358-392"],
    "legacyDetails": "Static condition metric. Condition = Base Condition - Injury Level (clamped >=0). All stats scaled TWICE by condition: stat = (base * cond/100) * (cond/100) \u2014 quadratic penalty. No active stamina drain during match. No sprint penalty. No recovery mechanic. Condition is snapshot at match start.",
    "legacyFiles": ["Player.cs:906-952", "Team.cs:438-446"],
    "gapAnalysis": "FM2026 is SIGNIFICANTLY MORE ADVANCED here. Active simulation with sprint drain, recovery, permanent decay. Legacy has no in-match fatigue \u2014 just static condition.\n\nFM2026 MISSING: Legacy's quadratic stat scaling. In Legacy, 50% condition = 25% effective stat (devastating). FM2026 only penalizes challenge probability, not passing/shooting/speed accuracy.",
    "codeSuggestions": "Add stamina-to-attribute scaling:\n// In playerStateController.js or a shared utility:\nfunction getEffectiveAttribute(player, attr, defaultVal) {\n  const base = player.attributes?.[attr] ?? defaultVal;\n  const ratio = player.stamina / player.staminaMax;\n  // Soft penalty: below 50% stamina starts degrading\n  const penalty = ratio > 0.5 ? 1.0 : 0.5 + ratio;\n  return base * penalty;\n}"
  },
  {
    "id": "cmp-024-injuries",
    "date": "2026-02-10",
    "feature": "In-Match Injuries",
    "existsInFM2026": "yes",
    "existsInLegacy": "yes",
    "priority": "P2",
    "status": "open",
    "fm2026Details": "Numeric severity model. Physique: (strength + staminaMax)*0.4. Risk factor: (100 - physique) + 20. Intensity: relSpeed/12 * intensityMod * (foul? 1.5:1.0). Base hazard: 0.2% + injury-prone bonus up to 10%. Micro-damage: 2-12 per tackle (accumulates). Severe at level 50+. 7 injury types weighted: minorknock(40), deadleg(25), calf_strain(15), hamstring_pull(10), dislocated_shoulder(5), broken_leg(3), cruciate_ligament(2). 'noprisoners' tactic multiplies damage by 1.6x.",
    "fm2026Files": ["challengeController.js:299-356"],
    "legacyDetails": "State-based system. 7 injury/stumble states: injuredOnBack, injuredOnFront, trippedForward, trippedGentle, takedive, recoverFromBack, recoverFromFront. Recovery tied to animation. Injury levels affect Condition metric (cumulative reduction). Injury trigger implicit in challenge outcomes.",
    "legacyFiles": ["PlayerActions.cs:tripped/injured states", "Player.cs"],
    "gapAnalysis": "FM2026 is MORE SOPHISTICATED: continuous numeric model, injury types with weighted probabilities, physique resilience, micro-damage accumulation.\nFM2026 MISSING: visual injury recovery states (no stumble/recovery animation feedback for replay).\nLegacy MISSING: injury type variety, physique calculation, damage accumulation.",
    "codeSuggestions": "No major fix needed. FM2026 injury model is more advanced. For replay rendering, add injury animation state:\n// After injury in challengeController.js:\nif (victim.injuryLevel > 25) {\n  victim.actionState = 'INJURED_GROUND';\n  victim.actionDuration = 3.0; // seconds on ground\n}"
  },
  {
    "id": "cmp-025-substitutions",
    "date": "2026-02-10",
    "feature": "Substitutions",
    "existsInFM2026": "yes",
    "existsInLegacy": "yes",
    "priority": "P2",
    "status": "open",
    "fm2026Details": "Advanced controller. Max 5 subs. Dead ball phase only. Staggered: WALKING_OFF \u2192 WALKING_ON (15s timeout each). Ball transfer, role transfer, position transfer. Extra time: +30s per sub. Auto-sub AI: injury (level>25), fatigue (after 45min if stamina<60), tactical (after 65min, increasing chance). Replacement: random bench player.",
    "fm2026Files": ["substitutionController.js:1-279"],
    "legacyDetails": "Simple FIFO queue. Validates player availability (not Disabled). Adds 12s injury time per sub. No AI auto-subs. Instant swap. No walking animation.",
    "legacyFiles": ["SubstitutionController.cs:1-76"],
    "gapAnalysis": "FM2026 is MORE ADVANCED: auto-sub AI, staggered animation, injury/fatigue triggers.\nFM2026 MISSING: Role-aware replacement selection (currently random bench player).\nLegacy MISSING: auto-sub AI, staggered execution, injury-based triggers.",
    "codeSuggestions": "Improve replacement selection:\n// In substitutionController.js autoSubCheck():\nconst sameRoleSub = bench.find(b => b.role === playerOff.role);\nconst replacement = sameRoleSub || bench[0]; // prefer same role"
  },
  {
    "id": "cmp-026-reaction-time",
    "date": "2026-02-10",
    "feature": "Player Reaction Time / BrainStamp",
    "existsInFM2026": "yes",
    "existsInLegacy": "yes",
    "priority": "P2",
    "status": "open",
    "fm2026Details": "Decision interval: base = 0.15 + (1-vision/100)*0.25 seconds (0.15-0.4s). Variance: 0.1 + (1-composure/100)*0.15 seconds. Random offset applied. Minimum: 0.25s. Post-tackle nudge: reduces to now+0.15s. State locking prevents rapid switching (PRESS 600ms, COVER 500ms, etc.).",
    "fm2026Files": ["playerStateController.js:115-133", "playerStateController.js:138-143"],
    "legacyDetails": "BrainStamp system. Reaction bias: 150 - IntelligenceStat. Out of play: 5 * bias game ticks. In play: 10 * bias game ticks (double penalty during live play). Player can only update when GameTime >= BrainStamp. Intelligence 50 = 500-1000 tick delay. Intelligence 100 = 250-500 tick delay. Intelligence 150 = instant.",
    "legacyFiles": ["PlayerActions.cs:170-177", "Player.cs:956"],
    "gapAnalysis": "Both have decision cooldown systems. FM2026 uses Vision+Composure (two attributes); Legacy uses Intelligence only. FM2026 range is 0.15-0.65s; Legacy has potentially much wider range. FM2026 adds randomness (composure variance); Legacy is deterministic.\n\nFM2026 BETTER: two-attribute system, randomness, post-tackle nudge\nLegacy BETTER: wider penalty range for low intelligence, in-play vs out-of-play distinction",
    "codeSuggestions": "Consider adding in-play vs dead-ball distinction:\n// In playerStateController.js computeDecisionInterval():\nconst inPlayMultiplier = matchState.phase === 'IN_PLAY' ? 1.0 : 0.5;\nreturn Math.max(0.15, (base + randomOffset) * inPlayMultiplier);"
  },
  {
    "id": "cmp-027-pressing",
    "date": "2026-02-10",
    "feature": "Pressing / Defensive AI",
    "existsInFM2026": "yes",
    "existsInLegacy": "partial",
    "priority": "P2",
    "status": "open",
    "fm2026Details": "Sophisticated system. Trigger: 12m base, 30m panic in own box. Role weights: DM 1.4x, ST 1.5x, CB 0.85x. Stamina factor: below 60% reduces to 0.4-1.0x. Support bonus: +0.2x per teammate within 8m (max 1.4x). Risk penalty: 0.7x if >1 opponent nearby. Slot cap: max 2 pressers. 3 variants: Challenging (<1.8m, threshold 0.45-0.7), Jockeying (1.8-8m, buffer 1-3m), Closing Down (all other). CB protection: avoid pressing wide balls >20m.",
    "fm2026Files": ["aiPress.js:1-278"],
    "legacyDetails": "Implicit in PlayerAI.cs and Team.cs. Team pressing flag (none/deep/high). Individual decision based on role, ball position, tactical flag. No explicit pressing score. No support bonus. No slot cap. No jockey/challenge distinction.",
    "legacyFiles": ["PlayerAI.cs", "Team.cs"],
    "gapAnalysis": "FM2026 is SIGNIFICANTLY MORE ADVANCED. Explicit scoring, 3 press variants, slot cap, support mechanics, role weighting, stamina integration. Legacy has basic implicit pressing only.\n\nFM2026 MISSING: direct use of team pressing flag (deep/high/none) as input to calculations.",
    "codeSuggestions": "Integrate team pressing flag:\n// In aiPress.js, in trigger calculation:\nconst pressingFlag = team.tactics?.pressing || 'none';\nconst flagMultiplier = { 'none': 0.5, 'deep': 0.8, 'high': 1.3 }[pressingFlag];\ntriggerDistance *= flagMultiplier;"
  },
  {
    "id": "cmp-028-chemistry",
    "date": "2026-02-10",
    "feature": "Communication / Chemistry System",
    "existsInFM2026": "partial",
    "existsInLegacy": "no",
    "priority": "P1",
    "status": "open",
    "fm2026Details": "TRACKING ONLY. Pass combinations tracked via playerFeeds: { 'playerId-receiverId': count }. Data stored in matchState and returned in match result. askingForBall flag in off-ball AI. But NO bonuses applied to pass accuracy, decision quality, or understanding. Chemistry data is collected but completely unused in AI decisions.",
    "fm2026Files": ["eventController.js:122-126", "matchMain.js:50", "matchMain.js:482", "aiOffBall.js:50-76"],
    "legacyDetails": "NOT IMPLEMENTED. No chemistry or communication tracking found. No player-pair relationship modifiers.",
    "legacyFiles": [],
    "gapAnalysis": "FM2026 has the infrastructure (tracking) but doesn't USE it. Legacy has nothing. This is a MAJOR opportunity \u2014 the data is already collected, just needs to be wired into pass scoring.\n\nNeither engine has chemistry influencing gameplay currently.",
    "codeSuggestions": "// Wire chemistry into aiPass.js evaluatePass():\nconst feedKey = `${passer.id}-${receiver.id}`;\nconst combinationCount = matchState.playerFeeds?.[feedKey] || 0;\n\n// Chemistry bonus: up to 15% better pass evaluation after repeated combinations\nconst chemistryBonus = 1.0 + Math.min(combinationCount * 0.025, 0.15);\nfinalScore *= chemistryBonus;\n\n// Also reduce lead error for familiar combinations:\nif (combinationCount >= 3) {\n  leadError *= 0.85; // 15% more accurate leading passes to familiar target\n}"
  },
  {
    "id": "cmp-029-match-flow",
    "date": "2026-02-10",
    "feature": "Match Flow / Game State Machine",
    "existsInFM2026": "yes",
    "existsInLegacy": "yes",
    "priority": "P2",
    "status": "open",
    "fm2026Details": "Two-level hierarchy: Phase (PRE_MATCH, IN_PLAY, DEAD_BALL, FINISHED) + PlayState (IDLE, LIVE, RESTART, GOAL, GOAL_CELEBRATION, HALF_TIME, PENALTY_SHOOTOUT, MATCH_OVER). 10 restart types. Restart substates: POSITIONING \u2192 READY \u2192 EXECUTED. Modular design with separate controllers. GOAL_PAUSE=2s.",
    "fm2026Files": ["matchFlowController.js:1-890", "constants.js:124-135"],
    "legacyDetails": "44 explicit states in monolithic enum. Monolithic switch-case in UpdateGameState(). Separate 'Awarded' and 'Execution' states for each restart type. GameStateStamp triggers timed transitions. Shootout support. All state logic in single 1,867-line file.",
    "legacyFiles": ["GameState.cs:14-44", "GameState.cs:210-1685"],
    "gapAnalysis": "FM2026 has fewer explicit states (~20 vs 44) but equivalent coverage through hierarchical design. More maintainable and modular. No critical gaps \u2014 just different architectural approach.\n\nBoth support: kickoff, throw-in, goal kick, corner, free kick, penalty, half-time, full-time, shootout.\nFM2026 MISSING: separate 'awarded' states (collapsed into RESTART + substate).",
    "codeSuggestions": "No fix needed. FM2026's hierarchical state design is cleaner than Legacy's monolithic approach."
  },
  {
    "id": "cmp-030-match-stats",
    "date": "2026-02-10",
    "feature": "Match Statistics Tracking",
    "existsInFM2026": "yes",
    "existsInLegacy": "yes",
    "priority": "P2",
    "status": "open",
    "fm2026Details": "Team stats: goals, shots, shotsOnTarget, passes, passesComplete, passesPercent, fouls, corners, crosses, offsides, tackles, yellowCards, redCards. Player stats: yellow_cards, red_cards, goals, assists, sheets, apps, subs, penalties, free_kicks, corners, throw_ins, crossing, tackles, injury_level, distance, shots, passes, fitness, ticksOnPitch. Event-driven via eventController.js.",
    "fm2026Files": ["eventController.js:55-189", "matchMain.js:51-54", "matchMain.js:114-120"],
    "legacyDetails": "Per-player: passesCompleted, passesMade, touches, crosses, assists, shotsMade, shotsOnTarget, goals, fouled, foulsMade, offside, headersWon, red, yellow, tacklesMade, tacklesWon, goalsConceded, saves. Team totals aggregated. Data streamed via TotalDataStream.",
    "legacyFiles": ["Team.cs:320-850"],
    "gapAnalysis": "FM2026 captures ~95% of Legacy stats. MISSING: player touch count (possessions/touches stat). FM2026 ADDS: injury tracking, combination chemistry logging, distance covered, fitness drain.\n\nMINOR gap only.",
    "codeSuggestions": "// Add touch count to eventController.js:\ncase 'BALL_TOUCH':\n  if (player) pStats.touches = (pStats.touches || 0) + 1;\n  break;"
  },
  {
    "id": "cmp-031-heatmap",
    "date": "2026-02-10",
    "feature": "Heat Map / Positional Tracking",
    "existsInFM2026": "yes",
    "existsInLegacy": "yes",
    "priority": "P2",
    "status": "open",
    "fm2026Details": "18x15 grid (5.83m x 4.53m cells). THREE channels: density (opponent pressure), attack (successful attacks), space (inverse of density). Decay: 95% per tick. Gaussian blur: 3x3 kernel (1.0 center, 0.4 edges). Attack heat recorded on goals (+10) and shots (+5). getSpace() query function for AI decisions.",
    "fm2026Files": ["heatMapController.js:1-120"],
    "legacyDetails": "15x18 grid (~4.5m x 5.8m cells). Basic float array. Population method referenced but not visible. Used in CalcPerformance and FindSpace(). Single channel (density only).",
    "legacyFiles": ["Team.cs:870-877"],
    "gapAnalysis": "FM2026 SIGNIFICANTLY ENHANCES Legacy: adds decay, Gaussian blur, attack success layer, space availability calculation. Legacy has basic grid only.\n\nNo gaps \u2014 FM2026 is superior here.",
    "codeSuggestions": "No fix needed. FM2026 heat map is well-designed and more advanced than Legacy."
  },
  {
    "id": "cmp-032-weak-foot",
    "date": "2026-02-10",
    "feature": "Weak Foot System",
    "existsInFM2026": "yes",
    "existsInLegacy": "no",
    "priority": "P2",
    "status": "open",
    "fm2026Details": "Comprehensive system. Player attributes: left_foot, right_foot, preferredFoot. Angle-based foot selection: smooth transition zone between FOOT_SWITCH_ANGLE_DEG_LOW and HIGH. Weak foot penalties: power reduction (FOOT_POWER_BASE + FOOT_POWER_SCALE * footStat/100), accuracy noise (exponential: FOOT_NOISE_INDEX power). Curl direction biased by preferred foot (sideMult). Test coverage: weakFootTest.js.",
    "fm2026Files": ["ballActionController.js:40-78", "ballEngine.js:183-211", "weakFootTest.js"],
    "legacyDetails": "NOT FOUND. No direct weak foot references in PlayerAI.cs or related files. If present, implementation is minimal or hidden.",
    "legacyFiles": [],
    "gapAnalysis": "FM2026 has COMPREHENSIVE weak foot system; Legacy has NONE found. FM2026 applies dual penalties (power + accuracy) based on angle relative to preferred foot.\n\nNo gap \u2014 FM2026 is superior here.",
    "codeSuggestions": "No fix needed. FM2026 weak foot system is well-implemented with test coverage."
  },
  {
    "id": "cmp-033-performance-rating",
    "date": "2026-02-10",
    "feature": "Player Performance Rating",
    "existsInFM2026": "no",
    "existsInLegacy": "yes",
    "priority": "P0",
    "status": "open",
    "fm2026Details": "NO match performance rating system. Has player confidence (40-95 range, attribute-based initialization) that modulates during match (goals +5, concede -10, save +8). But confidence is internal-only and DELETED from result output. No calculated rating number returned to frontend.",
    "fm2026Files": ["matchMain.js:122-127", "eventController.js:68-82", "matchMain.js:512-518"],
    "legacyDetails": "Full CalcPerformance() system. Base 50 points. 18+ scoring factors: good passes +7, bad passes -4, touches +5, goals +9, SOT +3.5, missed shots -1.5, assists +8, crosses +2, headers +3, yellow -5, red -15, fouls made -1, being fouled +2, offside -1. Role-dependent tackle scoring (defender +3, mid +2.2, other +0.6). GK: concede -7.5, save +7. Clean sheet: GK +10, def +9. Result multiplier: \u00b12% per goal diff. Clamped 30-100.",
    "legacyFiles": ["Team.cs:702-846"],
    "gapAnalysis": "CRITICAL GAP. FM2026 completely lacks a match-day player rating. Legacy returns a single 30-100 performance number per player. This affects:\n- Post-match UI (no ratings to display)\n- Player progression (no performance-based growth)\n- Man of the Match selection\n- Fan/media reactions\n\nAll the raw stats exist in FM2026 \u2014 just needs a rating formula.",
    "codeSuggestions": "// Add to matchMain.js, after stat collection:\n\nfunction calculatePerformanceRating(player, pStats, teamStats, resultDiff) {\n  let rating = 50;\n  \n  // Passing\n  const passAcc = pStats.passes > 0 ? pStats.passesComplete / pStats.passes : 0;\n  rating += passAcc * 7;\n  rating -= (pStats.passes - (pStats.passesComplete || 0)) * 0.5;\n  \n  // Attack\n  rating += (pStats.goals || 0) * 9;\n  rating += (pStats.assists || 0) * 8;\n  rating += (pStats.shots || 0) * 1.5;\n  \n  // Defense\n  rating += (pStats.tackles || 0) * 2;\n  \n  // Discipline\n  rating -= (pStats.yellow_cards || 0) * 5;\n  rating -= (pStats.red_cards || 0) * 15;\n  \n  // Clean sheet (defenders/GK)\n  if (teamStats.goals === 0 && ['GK','CB','LB','RB','LWB','RWB'].includes(player.role)) {\n    rating += player.role === 'GK' ? 10 : 9;\n  }\n  \n  // Result multiplier\n  rating *= 1 + (resultDiff * 0.02);\n  \n  return Math.round(Math.max(30, Math.min(100, rating)));\n}\n\n// Call after match ends, add to result:\nplayer.matchRating = calculatePerformanceRating(player, player.stats, teamStats, goalDiff);"
  }
];
